"""empty message

Revision ID: 02502548f5f0
Revises: ca0979deeaf0
Create Date: 2021-10-02 14:59:27.642157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02502548f5f0'
down_revision = 'ca0979deeaf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
