"""empty message

Revision ID: e1e19b378c48
Revises: 
Create Date: 2021-10-04 04:03:30.099781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e19b378c48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.String(length=140), nullable=True),
    sa.Column('answer1', sa.Integer(), nullable=True),
    sa.Column('question2', sa.String(length=140), nullable=True),
    sa.Column('answer2', sa.Integer(), nullable=True),
    sa.Column('question3', sa.String(length=140), nullable=True),
    sa.Column('answer3', sa.Integer(), nullable=True),
    sa.Column('question4', sa.String(length=140), nullable=True),
    sa.Column('answer4', sa.Integer(), nullable=True),
    sa.Column('question5', sa.String(length=140), nullable=True),
    sa.Column('answer5', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_timestamp'), 'quiz', ['timestamp'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer1', sa.Integer(), nullable=True),
    sa.Column('answer2', sa.Integer(), nullable=True),
    sa.Column('answer3', sa.Integer(), nullable=True),
    sa.Column('answer4', sa.Integer(), nullable=True),
    sa.Column('answer5', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('score', sa.String(length=140), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_timestamp'), 'answer', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_timestamp'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_quiz_timestamp'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
